import 'reflect-metadata';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir, tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { test } from 'node:test';
import { migrateH2, validateExport } from '../src/migrate-h2';
import { RecordsRepository } from '../src/records/records.repository';
import { SEED_RECORDS } from '../src/records/seed-data';

test('validates migration IDs, statuses, monetary values and identity sequence before importing', () => {
  const record = { ...SEED_RECORDS[0], id: 3 };
  assert.deepEqual(validateExport({ records: [record], nextId: 50 }), { records: [record], nextId: 50 });
  for (const exported of [null, {}, { records: [record], nextId: 3 },
    { records: [record, record], nextId: 50 }, { records: [{ ...record, status: 'Paid' }], nextId: 50 },
    { records: [{ ...record, amount: 1.001 }], nextId: 50 }]) {
    assert.throws(() => validateExport(exported));
  }
});

test('failed imports roll back all rows and preserve the existing database', () => {
  const repository = new RecordsRepository({ path: ':memory:', seed: false });
  try {
    const record = { ...SEED_RECORDS[0], id: 3 };
    assert.throws(() => repository.importRecords([record, record], 50));
    assert.deepEqual(repository.list(), []);
    repository.importRecords([record], 50);
    assert.throws(() => repository.importRecords([], 1), /overwrite/);
    assert.deepEqual(repository.list(), [record]);
    assert.equal(repository.create(SEED_RECORDS[0]).id, 50);
  } finally { repository.onModuleDestroy(); }
});

const jar = process.env.H2_JAR ?? join(homedir(), '.m2/repository/com/h2database/h2/2.3.232/h2-2.3.232.jar');
const hasJava = spawnSync('java', ['-version'], { stdio: 'ignore' }).status === 0;

test('migrates real H2 data, nulls, Unicode, decimals and deleted IDs without modifying the source', {
  skip: !existsSync(jar) || !hasJava ? 'Optional H2 migration integration test needs Java 21 and H2 2.3.232 (H2_JAR).' : false,
}, () => {
  const directory = mkdtempSync(join(tmpdir(), 'forma migration '));
  const source = join(directory, 'legacy');
  const target = join(directory, 'forma.sqlite');
  const hash = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');
  try {
    const fixture = join(directory, 'fixture.sql');
    writeFileSync(fixture, `
      CREATE TABLE BUSINESS_RECORD (
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, TYPE VARCHAR(255), NAME VARCHAR(255),
        COMPANY VARCHAR(255), EMAIL VARCHAR(255), STATUS VARCHAR(255), AMOUNT NUMERIC(38,2),
        DATE DATE, OWNER VARCHAR(255), QUANTITY INTEGER, NOTES VARCHAR(2000));
      INSERT INTO BUSINESS_RECORD VALUES (3, 'customers', 'Łódź 🧾', 'Test', NULL, 'Active', 9999999999.99,
        '2028-02-29', 'Alex Morgan', 0, 'Line one' || CHAR(10) || '"quoted", line two');
      INSERT INTO BUSINESS_RECORD VALUES (9, 'tasks', 'Task', 'Test', '', 'Done', 0.29,
        '2026-10-01', 'Alex Morgan', 2, NULL);
      ALTER TABLE BUSINESS_RECORD ALTER COLUMN ID RESTART WITH 50;`, 'utf8');
    execFileSync('java', ['-cp', jar, 'org.h2.tools.RunScript', '-url', `jdbc:h2:file:${source.replaceAll('\\', '/')}`,
      '-user', 'sa', '-password', 'forma-local', '-script', fixture], { stdio: 'pipe' });
    const before = hash(`${source}.mv.db`);
    const options = { source, target, jar, helper: resolve('scripts/ExportH2.java') };
    assert.equal(migrateH2(options), 2);
    assert.equal(hash(`${source}.mv.db`), before);
    assert.equal(hash(`${source}.mv.db.pre-nest-backup`), before);
    const repository = new RecordsRepository({ path: target });
    try {
      const records = repository.list();
      assert.deepEqual(records.map(r => r.id), [3, 9]);
      assert.equal(records[0].name, 'Łódź 🧾');
      assert.equal(records[0].notes, 'Line one\n"quoted", line two');
      assert.equal(records[0].email, null);
      assert.equal(records[0].amount, 9999999999.99);
      assert.equal(records[1].amount, 0.29);
      assert.equal(records[1].email, '');
      assert.equal(records[1].notes, null);
      assert.equal(repository.create(SEED_RECORDS[0]).id, 50);
    } finally { repository.onModuleDestroy(); }
    const migrated = hash(target);
    assert.throws(() => migrateH2(options), /overwrite/);
    assert.equal(hash(target), migrated);
    assert.equal(hash(`${source}.mv.db`), before);
  } finally { rmSync(directory, { recursive: true, force: true }); }
});
