import { RecordInput } from './business-record';

export const SEED_RECORDS: RecordInput[] = [
  {
    "type": "customers",
    "name": "Olivia Rhye",
    "company": "Layers",
    "email": "olivia@layers.design",
    "status": "Active",
    "amount": 48200,
    "date": "2026-09-28",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Design systems and digital experiences. Key account."
  },
  {
    "type": "customers",
    "name": "Phoenix Baker",
    "company": "Sisyphus",
    "email": "phoenix@sisyphus.com",
    "status": "Active",
    "amount": 36500,
    "date": "2026-09-25",
    "owner": "Jamie Lee",
    "quantity": 0,
    "notes": "Enterprise software partner."
  },
  {
    "type": "customers",
    "name": "Lana Steiner",
    "company": "Catalog",
    "email": "lana@catalog.studio",
    "status": "Lead",
    "amount": 24000,
    "date": "2026-09-24",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Interested in the annual growth package."
  },
  {
    "type": "customers",
    "name": "Demi Wilkinson",
    "company": "Circooles",
    "email": "demi@circooles.com",
    "status": "Active",
    "amount": 62800,
    "date": "2026-09-22",
    "owner": "Sam Wilson",
    "quantity": 0,
    "notes": "Quarterly business review due in October."
  },
  {
    "type": "customers",
    "name": "Drew Cano",
    "company": "Hourglass",
    "email": "drew@hourglass.io",
    "status": "Active",
    "amount": 18700,
    "date": "2026-09-19",
    "owner": "Jamie Lee",
    "quantity": 0,
    "notes": "Subscription renewal in November."
  },
  {
    "type": "customers",
    "name": "Natali Craig",
    "company": "Command+R",
    "email": "natali@commandr.com",
    "status": "Lead",
    "amount": 12500,
    "date": "2026-09-18",
    "owner": "Sam Wilson",
    "quantity": 0,
    "notes": "Discovery meeting scheduled."
  },
  {
    "type": "customers",
    "name": "Andi Lane",
    "company": "FocalPoint",
    "email": "andi@focalpoint.app",
    "status": "Inactive",
    "amount": 9800,
    "date": "2026-09-12",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Follow up next quarter."
  },
  {
    "type": "deals",
    "name": "Enterprise platform",
    "company": "Layers",
    "email": "",
    "status": "Negotiation",
    "amount": 24500,
    "date": "2026-10-12",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Final pricing discussion."
  },
  {
    "type": "deals",
    "name": "Brand workspace",
    "company": "Catalog",
    "email": "",
    "status": "Proposal",
    "amount": 18000,
    "date": "2026-10-18",
    "owner": "Jamie Lee",
    "quantity": 0,
    "notes": "Proposal shared with the design team."
  },
  {
    "type": "deals",
    "name": "Team expansion",
    "company": "Sisyphus",
    "email": "",
    "status": "Qualified",
    "amount": 12800,
    "date": "2026-10-22",
    "owner": "Sam Wilson",
    "quantity": 0,
    "notes": "Add 40 seats to the workspace."
  },
  {
    "type": "deals",
    "name": "Annual renewal",
    "company": "Circooles",
    "email": "",
    "status": "Won",
    "amount": 32000,
    "date": "2026-09-27",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Signed for another year."
  },
  {
    "type": "deals",
    "name": "Analytics suite",
    "company": "Hourglass",
    "email": "",
    "status": "Proposal",
    "amount": 9600,
    "date": "2026-10-25",
    "owner": "Jamie Lee",
    "quantity": 0,
    "notes": "Custom reporting integration."
  },
  {
    "type": "deals",
    "name": "Growth package",
    "company": "Command+R",
    "email": "",
    "status": "Qualified",
    "amount": 15000,
    "date": "2026-10-29",
    "owner": "Sam Wilson",
    "quantity": 0,
    "notes": "Discovery completed."
  },
  {
    "type": "deals",
    "name": "Studio rollout",
    "company": "FocalPoint",
    "email": "",
    "status": "Negotiation",
    "amount": 8400,
    "date": "2026-10-15",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Legal review in progress."
  },
  {
    "type": "invoices",
    "name": "INV-2026-001",
    "company": "Layers",
    "email": "",
    "status": "Paid",
    "amount": 18400,
    "date": "2026-04-15",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Monthly services. USD."
  },
  {
    "type": "invoices",
    "name": "INV-2026-002",
    "company": "Sisyphus",
    "email": "",
    "status": "Paid",
    "amount": 24600,
    "date": "2026-05-15",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Monthly services. USD."
  },
  {
    "type": "invoices",
    "name": "INV-2026-003",
    "company": "Catalog",
    "email": "",
    "status": "Paid",
    "amount": 21800,
    "date": "2026-06-15",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Monthly services. USD."
  },
  {
    "type": "invoices",
    "name": "INV-2026-004",
    "company": "Circooles",
    "email": "",
    "status": "Paid",
    "amount": 31200,
    "date": "2026-07-15",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Monthly services. USD."
  },
  {
    "type": "invoices",
    "name": "INV-2026-005",
    "company": "Hourglass",
    "email": "",
    "status": "Paid",
    "amount": 28400,
    "date": "2026-08-15",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Monthly services. USD."
  },
  {
    "type": "invoices",
    "name": "INV-2026-006",
    "company": "Command+R",
    "email": "",
    "status": "Paid",
    "amount": 38600,
    "date": "2026-09-15",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Monthly services. USD."
  },
  {
    "type": "invoices",
    "name": "INV-2026-007",
    "company": "Layers",
    "email": "",
    "status": "Sent",
    "amount": 12400,
    "date": "2026-10-12",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Payment due within 30 days."
  },
  {
    "type": "invoices",
    "name": "INV-2026-008",
    "company": "Catalog",
    "email": "",
    "status": "Overdue",
    "amount": 6800,
    "date": "2026-09-25",
    "owner": "Jamie Lee",
    "quantity": 0,
    "notes": "Payment reminder required."
  },
  {
    "type": "invoices",
    "name": "INV-2026-009",
    "company": "Hourglass",
    "email": "",
    "status": "Draft",
    "amount": 4200,
    "date": "2026-10-20",
    "owner": "Sam Wilson",
    "quantity": 0,
    "notes": "Review before sending."
  },
  {
    "type": "products",
    "name": "Workspace Pro",
    "company": "Software",
    "email": "",
    "status": "In stock",
    "amount": 79,
    "date": "2026-10-01",
    "owner": "Alex Morgan",
    "quantity": 240,
    "notes": "Per-seat annual workspace license."
  },
  {
    "type": "products",
    "name": "Analytics Plus",
    "company": "Software",
    "email": "",
    "status": "In stock",
    "amount": 149,
    "date": "2026-10-01",
    "owner": "Jamie Lee",
    "quantity": 85,
    "notes": "Advanced reporting add-on."
  },
  {
    "type": "products",
    "name": "Studio Desk Kit",
    "company": "Hardware",
    "email": "",
    "status": "Low stock",
    "amount": 249,
    "date": "2026-10-01",
    "owner": "Sam Wilson",
    "quantity": 8,
    "notes": "Desk accessories and docking hub."
  },
  {
    "type": "products",
    "name": "Conference Hub",
    "company": "Hardware",
    "email": "",
    "status": "Out of stock",
    "amount": 599,
    "date": "2026-10-01",
    "owner": "Sam Wilson",
    "quantity": 0,
    "notes": "All-in-one meeting room solution."
  },
  {
    "type": "tasks",
    "name": "Send proposal to Catalog",
    "company": "Catalog",
    "email": "",
    "status": "To do",
    "amount": 0,
    "date": "2026-10-01",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Include the annual billing option."
  },
  {
    "type": "tasks",
    "name": "Quarterly review with Layers",
    "company": "Layers",
    "email": "",
    "status": "In progress",
    "amount": 0,
    "date": "2026-10-01",
    "owner": "Alex Morgan",
    "quantity": 0,
    "notes": "Prepare usage and growth report."
  },
  {
    "type": "tasks",
    "name": "Follow up on overdue invoice",
    "company": "Catalog",
    "email": "",
    "status": "To do",
    "amount": 0,
    "date": "2026-10-02",
    "owner": "Jamie Lee",
    "quantity": 0,
    "notes": "Contact the finance department."
  },
  {
    "type": "tasks",
    "name": "Onboard Circooles team",
    "company": "Circooles",
    "email": "",
    "status": "Done",
    "amount": 0,
    "date": "2026-09-30",
    "owner": "Sam Wilson",
    "quantity": 0,
    "notes": "Training and setup completed."
  }
];
